# Generated by Django 4.2 on 2023-04-10 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Symptoms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pain_level', models.CharField(choices=[('M', 'Moderate'), ('L', 'Mild'), ('S', 'Severe')], default='L', max_length=1)),
                ('pain_location', models.CharField(choices=[('UF', 'Upper Jaw Front'), ('UB', 'Upper Jaw Back'), ('LF', 'Lower Jaw Front'), ('LB', 'Lower Jaw Back'), ('N', 'none')], default='N', max_length=2)),
                ('pain_description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('email', models.CharField(unique=True)),
                ('password', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_name', models.CharField(max_length=150)),
                ('treatment_description', models.CharField(max_length=500)),
                ('Symptoms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment', to='floss.symptoms')),
            ],
        ),
    ]
