# Generated by Django 4.2 on 2023-04-11 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floss', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treatment',
            old_name='Symptoms',
            new_name='Symptom',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
