# Generated by Django 4.2 on 2023-04-11 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floss', '0002_rename_symptoms_treatment_symptom_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptoms',
            name='pain_type',
            field=models.CharField(choices=[('T', 'throbbing'), ('A', 'aching'), ('BG', 'bleeding gums'), ('SW', 'swelling'), ('TS', 'temperature sensitive'), ('N', 'none')], default='N', max_length=100),
        ),
    ]
