# Generated by Django 4.2 on 2023-04-16 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floss', '0004_remove_symptoms_pain_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptoms',
            name='date',
            field=models.CharField(default='04/15/2023', max_length=100),
        ),
    ]
