# Generated by Django 4.2 on 2023-04-17 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floss', '0006_alter_symptoms_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptoms',
            name='pain_level',
            field=models.CharField(choices=[('Moderate', 'Moderate'), ('Mild', 'Mild'), ('Severe', 'Severe')], default='L', max_length=20),
        ),
        migrations.AlterField(
            model_name='symptoms',
            name='pain_location',
            field=models.CharField(choices=[('Upper Jaw Front', 'Upper Jaw Front'), ('Upper Jaw Back', 'Upper Jaw Back'), ('Lower Jaw Front', 'Lower Jaw Front'), ('Lower Jaw Back', 'Lower Jaw Back'), ('None', 'none')], default='None', max_length=25),
        ),
        migrations.AlterField(
            model_name='symptoms',
            name='pain_type',
            field=models.CharField(choices=[('Throbbing', 'throbbing'), ('Aching', 'aching'), ('Bleeding Gums', 'bleeding gums'), ('Swelling', 'swelling'), ('Temp. Sensitive', 'temperature sensitive'), ('None', 'none')], default='None', max_length=100),
        ),
    ]
